#!/bin/sh
# -*- mode: sh -*-

# Usage :
# dos2mac FILE [...]

progname=${0##*/}
tempfile=$(mktemp $progname.XXXXXX) || exit 5
for file
do
    tr -d '\012' < "$file" > "$tempfile" &&
        mv "$tempfile" "$file"
done
