#!/bin/sh
# -*- mode: sh -*-

# Usage :
# unix2dos FILE [...]

progname=${0##*/}
CR=$(printf "\r")
tempfile=$(mktemp $progname.XXXXXX) || exit 5
for file
do
    sed -e "s/$/$CR/" -e "s/$CR$CR$/$CR/" "$file" > "$tempfile" &&
        mv "$tempfile" "$file"
done
